version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: app-db
    environment:
      POSTGRES_USER: APP
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: APP
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U APP"]
      interval: 10s
      retries: 5